# Generated by Django 2.2.12 on 2020-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='doctor_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='health_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='medicince_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='servere_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
