# Generated by Django 2.2.12 on 2020-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='role',
            field=models.TextField(default='patient'),
        ),
    ]
