# Generated by Django 2.2.12 on 2020-04-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='user_id',
        ),
    ]
