# Generated by Django 2.2.12 on 2020-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20200425_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoomus_meeting_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
