# Generated by Django 2.2.12 on 2020-04-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoom', '0004_auto_20200425_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='user_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_meeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to=settings.AUTH_USER_MODEL),
        ),
    ]
